services:

  db:
    image: postgres:13.3  
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: pokedex
    volumes:
      - db-data:/var/lib/postgresql/data

  # Serviço do Adminer para gerenciar o banco de dados
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Serviço do backend
  backend:
    build:
      context: ./back  
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: example
      DATABASE_NAME: pokedex
      RAILS_ENV: development
      DATABASE_URL: postgresql://user:example@db:5432/pokedex
      RAILS_MASTER_KEY: feabca1b7b352169ab917816a3007a81

  # Serviço do frontend
  frontend:
    build:
      context: ./front
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  db-data:
